name: Publish library to NPM

on:
  release:
    types: [published]

jobs:
  publish-npm:
    if: startsWith(github.event.release.name, '@storyblok/app-extension-auth@')
    name: Publish library to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
